import base64
import colorsys
import hashlib
import io

import streamlit as st

from flower import (
    DahliaParams, generate_flower,
    RedRoseParams, generate_red_rose,
    WaterLilyParams, generate_water_lily,
)
from garden.render import compose_with_stem


def _name_seed(name: str) -> int:
    return int(hashlib.md5(name.lower().strip().encode()).hexdigest()[:8], 16)


def name_to_colors(name: str) -> tuple[tuple[float, float, float], tuple[float, float, float]]:
    """Deterministically map a name to (color_inner, color_outer) RGB tuples for the Dahlia."""
    hue = (_name_seed(name) % 10000) / 10000.0
    color_inner = colorsys.hls_to_rgb(hue, 0.35, 0.90)
    color_outer = colorsys.hls_to_rgb((hue + 0.08) % 1.0, 0.85, 0.55)
    return color_inner, color_outer


# Real water-lily colour families: (inner pad, inner petal, mid petal, tip)
_LILY_PALETTES: list[tuple[str, str, str, str]] = [
    ("#b8d4a0", "#d8f0c8", "#f5f0ee", "#e0d4c0"),  # white / cream
    ("#b8d4a0", "#d5ebbd", "#f5c0d0", "#d4607a"),  # pink
    ("#b8d4a0", "#d5ebbd", "#c8a0d8", "#7030a0"),  # purple
    ("#c7d49c", "#d5ebbd", "#f8e70c", "#bf5700"),  # yellow (original)
    ("#b8d4a0", "#d0e8c8", "#f0a0c8", "#b02870"),  # magenta
    ("#b8d4a0", "#d5ebbd", "#a8c8e8", "#3870b0"),  # blue / lavender
]


def name_to_lily_colors(name: str) -> tuple[str, str, str, str]:
    """Pick one of the real water-lily colour palettes deterministically from the name."""
    return _LILY_PALETTES[_name_seed(name) % len(_LILY_PALETTES)]


def _to_hex(rgb: tuple[float, float, float]) -> str:
    return "#{:02x}{:02x}{:02x}".format(*(int(c * 255) for c in rgb))


st.set_page_config(page_title="My Flower", layout="wide")
st.title("Generate your flower")

if "flower_b64" not in st.session_state:
    st.markdown("""
Each flower here is a 3D parametric surface, basically a mathematical object living in space,
rendered from a viewpoint and projected onto your screen. 

For the **Dahlia**, petals are generated by sweeping a curved surface around a spiral
using the Fermat spiral equation. The angle each petal sits at, how far it opens,
and how many complete the bloom are all governed by a handful of numbers — the sliders
you can tune on the left. The **Water Lily** uses a Fibonacci spiral to arrange petals
radially outward, each one shaped by a smooth polar mesh.

What makes *your* flower yours is colour. Your name is passed through a hash function
(MD5) — a deterministic but unpredictable mapping — turning a string of letters into a
number. That number becomes a hue on the colour wheel, and from it your unique inner and
outer petal colours are derived. Same name, same flower, every time; different name,
entirely different bloom.

---

*With these choices from you, and simply because of your name, your flower is uniquely
beautiful — just like you.*

---
<small>Flower equations by **Eric Ludlam** & translations from MATLAB to Python by **Mohammad Aryayi**.</small>
""", unsafe_allow_html=True)

with st.sidebar:
    name = st.text_input("Your name", placeholder="e.g. Marie",
                         help="For the Dahlia, your name also determines your unique petal colours")

    _is_michelle = name.strip().lower() == "michelle"
    if _is_michelle:
        st.success("Oh hello my love! Everyone gets to choose between dahlia or water lily, but you get a different option 🌹❤️")
    _options = ["Dahlia", "Water Lily"] + (["🌹 Rose"] if _is_michelle else [])
    flower_type = st.selectbox("Flower type", _options, index=None, placeholder="Choose a flower…")

    if flower_type is None:
        st.info("Choose a flower type above to get started.")

    elif flower_type == "Dahlia":
        ci, co = name_to_colors(name or "Anonymous")
        hex_ci, hex_co = _to_hex(ci), _to_hex(co)
        st.markdown(
            f"**Your colour palette** &nbsp;"
            f'<span style="background:{hex_ci};border-radius:3px;padding:2px 14px">&nbsp;</span>'
            f" inner &nbsp;&nbsp;"
            f'<span style="background:{hex_co};border-radius:3px;padding:2px 14px">&nbsp;</span>'
            f" outer",
            unsafe_allow_html=True,
        )
        if not name:
            st.caption("Enter your name above to get your personal colours.")

        st.header("Shape")
        ppr = st.slider(
            "Petals per revolution", 5.0, 20.0, 12.6,
            help="How many petals complete one full spiral turn — higher = denser, more tightly packed spiral",
        )
        pn = st.slider(
            "Total petals", 50, 250, 140, step=10,
            help="Total number of petals on the flower — more petals create a fuller, rounder bloom",
        )
        pf = st.slider(
            "Petal tilt", -2.5, 0.0, -1.2,
            help="How much the petal tips angle outward — more negative = petals splay wider open",
        )
        ol_in = st.slider(
            "Inner openness", 0.01, 0.5, 0.11,
            help="Curvature at the centre of the flower — lower = tighter, more closed bud",
        )
        ol_out = st.slider(
            "Outer openness", 0.5, 2.5, 1.1,
            help="Curvature at the petal tips — higher = flatter, more open bloom",
        )

    elif flower_type == "🌹 Rose":
        st.header("Shape")
        ppr = st.slider(
            "Petals per revolution", 1.0, 8.0, 3.6,
            help="Spiral density of the petals — lower = looser, more spread-out arrangement",
        )
        pn = st.slider(
            "Total petals", 10, 80, 40, step=5,
            help="Total number of petals — more petals create a fuller, more layered rose",
        )
        pf = st.slider(
            "Petal curl", 0.5, 5.0, 2.0,
            help="How much the petals cup and curl upward at their tips",
        )
        ps = st.slider(
            "Petal separation", 0.5, 2.0, 1.25,
            help="Overlap between adjacent petals — lower = petals blend together, higher = each petal is more distinct",
        )
        ol_in = st.slider(
            "Inner openness", 0.05, 0.5, 0.2,
            help="How tightly closed the centre of the rose is — lower = tight bud",
        )
        ol_out = st.slider(
            "Outer openness", 0.5, 2.0, 1.02,
            help="How far the outermost petals spread — higher = more open, relaxed bloom",
        )

    elif flower_type == "Water Lily":
        _lily_colors = name_to_lily_colors(name or "Anonymous")
        st.markdown(
            f"**Your lily palette** &nbsp;"
            + " ".join(
                f'<span style="background:{c};border-radius:3px;padding:2px 10px">&nbsp;</span>'
                for c in _lily_colors
            ),
            unsafe_allow_html=True,
        )
        if not name:
            st.caption("Enter your name above to get your personal colours.")

        st.header("Shape")
        npetals = st.slider(
            "Number of petals", 20, 120, 60, step=5,
            help="Total petals arranged in a Fibonacci spiral — more petals create a denser, more ornate lily",
        )
        vpp = st.slider(
            "Petal width detail", 10, 40, 23,
            help="Mesh resolution along the width of each petal — higher = smoother petal edges (slower to render)",
        )
        vrpp = st.slider(
            "Petal depth detail", 5, 30, 15,
            help="Mesh resolution along the length of each petal — higher = smoother petal curves (slower to render)",
        )

    clicked = st.button("Generate", type="primary", use_container_width=True,
                        disabled=flower_type is None)

if clicked and flower_type is not None:
    if flower_type == "Dahlia":
        ci, co = name_to_colors(name or "Anonymous")
        params = DahliaParams(
            petals_per_revolution=ppr,
            total_petals=pn,
            petal_tilt=pf,
            openness=(ol_in, ol_out),
            color_inner=ci,
            color_outer=co,
        )
        fig = generate_flower(params)
    elif flower_type == "🌹 Rose":
        params = RedRoseParams(
            petals_per_revolution=ppr,
            total_petals=pn,
            petal_tilt=pf,
            petal_separation=ps,
            openness=(ol_in, ol_out),
        )
        fig = generate_red_rose(params)
    else:
        params = WaterLilyParams(
            num_petals=npetals,
            vertices_per_petal_theta=vpp,
            vertices_per_petal_r=vrpp,
            petal_colors=name_to_lily_colors(name or "Anonymous"),
        )
        fig = generate_water_lily(params)

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=150, bbox_inches="tight", transparent=True)
    # Water lilies float on water — no stem
    if flower_type == "Water Lily":
        image_bytes = buf.getvalue()
    else:
        image_bytes = compose_with_stem(buf.getvalue())

    # Store in session state so the Garden page can use it
    st.session_state["flower_params"] = params
    st.session_state["flower_b64"] = base64.b64encode(image_bytes).decode()
    st.session_state["flower_name"] = name or "Anonymous"

    col, _ = st.columns([1, 1])
    with col:
        st.pyplot(fig)
        st.download_button("Download PNG", image_bytes, "my_flower.png", "image/png")
        if name:
            st.success("Head to the Garden page to plant your flower!")
        else:
            st.info("Enter your name above to be able to plant it in the garden.")
