import base64
import colorsys
import hashlib
import io

import streamlit as st

from flower import (
    DahliaParams, generate_flower,
    RedRoseParams, generate_red_rose,
    WaterLilyParams, generate_water_lily,
)
from garden.render import compose_with_stem


def _name_seed(name: str) -> int:
    return int(hashlib.md5(name.lower().strip().encode()).hexdigest()[:8], 16)


def name_to_colors(name: str) -> tuple[tuple[float, float, float], tuple[float, float, float]]:
    """Deterministically map a name to (color_inner, color_outer) RGB tuples for the Dahlia."""
    hue = (_name_seed(name) % 10000) / 10000.0
    color_inner = colorsys.hls_to_rgb(hue, 0.35, 0.90)
    color_outer = colorsys.hls_to_rgb((hue + 0.08) % 1.0, 0.85, 0.55)
    return color_inner, color_outer


# Real water-lily colour families: (inner pad, inner petal, mid petal, tip)
_LILY_PALETTES: list[tuple[str, str, str, str]] = [
    ("#b8d4a0", "#d8f0c8", "#f5f0ee", "#e0d4c0"),  # white / cream
    ("#b8d4a0", "#d5ebbd", "#f5c0d0", "#d4607a"),  # pink
    ("#b8d4a0", "#d5ebbd", "#c8a0d8", "#7030a0"),  # purple
    ("#c7d49c", "#d5ebbd", "#f8e70c", "#bf5700"),  # yellow (original)
    ("#b8d4a0", "#d0e8c8", "#f0a0c8", "#b02870"),  # magenta
    ("#b8d4a0", "#d5ebbd", "#a8c8e8", "#3870b0"),  # blue / lavender
]


def name_to_lily_colors(name: str) -> tuple[str, str, str, str]:
    """Pick one of the real water-lily colour palettes deterministically from the name."""
    return _LILY_PALETTES[_name_seed(name) % len(_LILY_PALETTES)]


def _to_hex(rgb: tuple[float, float, float]) -> str:
    return "#{:02x}{:02x}{:02x}".format(*(int(c * 255) for c in rgb))


st.set_page_config(page_title="My Flower", layout="wide")

fr = st.toggle("🇫🇷 Français", value=False)

if fr:
    st.title("Génère ta fleur")
else:
    st.title("Generate your flower")

if "flower_b64" not in st.session_state:
    if not fr:
        st.markdown("""
Each flower created is a 3D parametric surface, basically a mathematical object living in space,
rendered from a viewpoint and projected onto your screen.

I have to give credit to **Eric Ludlam**, a much smarter guy than me, who came up with the code to
implement equations that lead to the creation of these flowers!

For the **Dahlia**, petals are generated by sweeping a curved surface around a spiral
using the Fermat spiral equation (I'm not fully sure how this all works lol).
The angle each petal sits at, how far it opens,
and how many complete the bloom are all governed by a handful of numbers: the sliders
you can tune on the left. The **Water Lily** uses a Fibonacci spiral to arrange petals
radially outward, each one shaped by a smooth polar mesh.
                    
Don't hesistate to play around with the options and generate different flowers! The one you will bring
to the garden will always be the last generated.

What also makes your flower unique is colour! Your name is passed through a hash function
(MD5), deterministic but unpredictable mapping, turning a word into a
number. That number becomes a hue on the colour wheel, and from it your unique inner and
outer petal colours are derived. The cool thing is that the same name will always lead to the
same colours, every time; and a different name will lead to an entirely different bloom.

*Each flower will be unique, just like you!*
""", unsafe_allow_html=True)
    else:
        st.markdown("""
Chaque fleur créée est une surface paramétrique 3D, un objet mathématique qui vit dans l'espace,
rendu depuis un point de vue et projeté sur ton écran.

Je dois créditer **Eric Ludlam**, qui est bien plus intelligent que moi, et qui a écrit le code
implémentant les équations à l'origine de ces fleurs !

Pour le **Dahlia**, les pétales sont générés en balayant une surface courbe autour d'une spirale
grâce à l'équation de la spirale de Fermat (honnêtement je capte pas tout mdr).
L'angle de chaque pétale, son ouverture et le nombre total de pétales sont tous contrôlés
par quelques paramètres : les curseurs que tu peux ajuster à gauche. Le **Nénuphar** utilise
une spirale de Fibonacci pour disposer les pétales vers l'extérieur, chacun formé par un maillage polaire lisse.

N'hésite pas à jouer avec les options pour générer differentes fleurs! Celle que tu emmèneras au jardin sera
toujours la dernière créée.             

Ce qui rend ta fleur unique, c'est la couleur ! Ton prénom est passé dans une fonction de hachage
(MD5), un mapping déterministe mais imprévisible, qui transforme un mot en nombre.
Ce nombre devient une teinte sur la roue des couleurs, et à partir de là tes couleurs de pétales
intérieures et extérieures sont dérivées. La partie sympa, c'est que le même prénom donnera toujours
les mêmes couleurs ; et un prénom différent donnera une fleur entièrement différente.

*Chaque fleur sera unique, comme toi !*
""", unsafe_allow_html=True)

with st.sidebar:
    name = st.text_input(
        "Ton prénom" if fr else "Your name",
        placeholder="ex. Juliette" if fr else "e.g. Juliette",
        help="Ton prénom détermine tes couleurs de pétales uniques" if fr else "Your name determines your unique petal colours",
    )

    _is_michelle = name.strip().lower() == "michelle"
    if _is_michelle:
        if fr:
            st.success("Oh bonjour mon amour ! Tout le monde peut choisir entre dahlia ou nénuphar, mais toi tu as une option supplémentaire 🌹❤️")
        else:
            st.success("Oh hello my love! Everyone gets to choose between dahlia or water lily, but you get a different option 🌹❤️")

    if fr:
        _options = ["Dahlia", "Nénuphar"] + (["🌹 Rose"] if _is_michelle else [])
        flower_type = st.selectbox("Type de fleur", _options, index=None, placeholder="Choisis une fleur…")
    else:
        _options = ["Dahlia", "Water Lily"] + (["🌹 Rose"] if _is_michelle else [])
        flower_type = st.selectbox("Flower type", _options, index=None, placeholder="Choose a flower…")

    # Normalise French flower type names back to internal keys
    _flower_key = {"Nénuphar": "Water Lily"}.get(flower_type, flower_type)

    if flower_type is None:
        st.info("Choisis un type de fleur ci-dessus pour commencer." if fr else "Choose a flower type above to get started.")

    elif _flower_key == "Dahlia":
        ci, co = name_to_colors(name or "Anonymous")
        hex_ci, hex_co = _to_hex(ci), _to_hex(co)
        _inner_label = "intérieur" if fr else "inner"
        _outer_label = "extérieur" if fr else "outer"
        _palette_label = "Ta palette de couleurs" if fr else "Your colour palette"
        st.markdown(
            f"**{_palette_label}** &nbsp;"
            f'<span style="background:{hex_ci};border-radius:3px;padding:2px 14px">&nbsp;</span>'
            f" {_inner_label} &nbsp;&nbsp;"
            f'<span style="background:{hex_co};border-radius:3px;padding:2px 14px">&nbsp;</span>'
            f" {_outer_label}",
            unsafe_allow_html=True,
        )
        if not name:
            st.caption("Entre ton prénom ci-dessus pour obtenir tes couleurs personnelles." if fr else "Enter your name above to get your personal colours.")

        st.header("Forme" if fr else "Shape")
        ppr = st.slider(
            "Pétales par tour" if fr else "Petals per revolution", 5.0, 20.0, 12.6,
            help="Combien de pétales forment un tour de spirale — plus élevé = spirale plus dense et serrée" if fr else "How many petals complete one full spiral turn — higher = denser, more tightly packed spiral",
        )
        pn = st.slider(
            "Nombre de pétales" if fr else "Total petals", 50, 250, 140, step=10,
            help="Nombre total de pétales — plus de pétales créent une fleur plus pleine et ronde" if fr else "Total number of petals on the flower — more petals create a fuller, rounder bloom",
        )
        pf = st.slider(
            "Inclinaison des pétales" if fr else "Petal tilt", -2.5, 0.0, -1.2,
            help="À quel point les pointes des pétales s'ouvrent vers l'extérieur — plus négatif = pétales plus étalés" if fr else "How much the petal tips angle outward — more negative = petals splay wider open",
        )
        ol_in = st.slider(
            "Ouverture intérieure" if fr else "Inner openness", 0.01, 0.5, 0.11,
            help="Courbure au centre de la fleur — plus bas = bouton plus fermé" if fr else "Curvature at the centre of the flower — lower = tighter, more closed bud",
        )
        ol_out = st.slider(
            "Ouverture extérieure" if fr else "Outer openness", 0.5, 2.5, 1.1,
            help="Courbure aux pointes des pétales — plus élevé = fleur plus plate et ouverte" if fr else "Curvature at the petal tips — higher = flatter, more open bloom",
        )

    elif _flower_key == "🌹 Rose":
        st.header("Forme" if fr else "Shape")
        ppr = st.slider(
            "Pétales par tour" if fr else "Petals per revolution", 1.0, 8.0, 3.6,
            help="Densité de la spirale des pétales — plus bas = disposition plus lâche et étalée" if fr else "Spiral density of the petals — lower = looser, more spread-out arrangement",
        )
        pn = st.slider(
            "Nombre de pétales" if fr else "Total petals", 10, 80, 40, step=5,
            help="Nombre total de pétales — plus de pétales créent une rose plus pleine et feuilletée" if fr else "Total number of petals — more petals create a fuller, more layered rose",
        )
        pf = st.slider(
            "Enroulement des pétales" if fr else "Petal curl", 0.5, 5.0, 2.0,
            help="À quel point les pétales se courbent et s'enroulent vers le haut à leurs pointes" if fr else "How much the petals cup and curl upward at their tips",
        )
        ps = st.slider(
            "Séparation des pétales" if fr else "Petal separation", 0.5, 2.0, 1.25,
            help="Chevauchement entre pétales adjacents — plus bas = pétales fondus, plus haut = pétales distincts" if fr else "Overlap between adjacent petals — lower = petals blend together, higher = each petal is more distinct",
        )
        ol_in = st.slider(
            "Ouverture intérieure" if fr else "Inner openness", 0.05, 0.5, 0.2,
            help="À quel point le centre de la rose est fermé — plus bas = bouton serré" if fr else "How tightly closed the centre of the rose is — lower = tight bud",
        )
        ol_out = st.slider(
            "Ouverture extérieure" if fr else "Outer openness", 0.5, 2.0, 1.02,
            help="À quel point les pétales extérieurs s'ouvrent — plus élevé = fleur plus ouverte et détendue" if fr else "How far the outermost petals spread — higher = more open, relaxed bloom",
        )

    elif _flower_key == "Water Lily":
        _lily_colors = name_to_lily_colors(name or "Anonymous")
        _lily_label = "Ta palette de nénuphar" if fr else "Your lily palette"
        st.markdown(
            f"**{_lily_label}** &nbsp;"
            + " ".join(
                f'<span style="background:{c};border-radius:3px;padding:2px 10px">&nbsp;</span>'
                for c in _lily_colors
            ),
            unsafe_allow_html=True,
        )
        if not name:
            st.caption("Entre ton prénom ci-dessus pour obtenir tes couleurs personnelles." if fr else "Enter your name above to get your personal colours.")

        st.header("Forme" if fr else "Shape")
        npetals = st.slider(
            "Nombre de pétales" if fr else "Number of petals", 20, 120, 60, step=5,
            help="Pétales totaux disposés en spirale de Fibonacci — plus de pétales = nénuphar plus dense" if fr else "Total petals arranged in a Fibonacci spiral — more petals create a denser, more ornate lily",
        )
        vpp = st.slider(
            "Détail largeur des pétales" if fr else "Petal width detail", 10, 40, 23,
            help="Résolution du maillage en largeur — plus élevé = bords de pétales plus lisses (plus lent)" if fr else "Mesh resolution along the width of each petal — higher = smoother petal edges (slower to render)",
        )
        vrpp = st.slider(
            "Détail profondeur des pétales" if fr else "Petal depth detail", 5, 30, 15,
            help="Résolution du maillage en longueur — plus élevé = courbes de pétales plus lisses (plus lent)" if fr else "Mesh resolution along the length of each petal — higher = smoother petal curves (slower to render)",
        )

    clicked = st.button(
        "Générer" if fr else "Generate",
        type="primary", use_container_width=True,
        disabled=flower_type is None,
    )

if clicked and flower_type is not None:
    with st.spinner("Ta fleur pousse…" if fr else "Growing your flower…"):
        if _flower_key == "Dahlia":
            ci, co = name_to_colors(name or "Anonymous")
            params = DahliaParams(
                petals_per_revolution=ppr,
                total_petals=pn,
                petal_tilt=pf,
                openness=(ol_in, ol_out),
                color_inner=ci,
                color_outer=co,
            )
            fig = generate_flower(params)
        elif _flower_key == "🌹 Rose":
            params = RedRoseParams(
                petals_per_revolution=ppr,
                total_petals=pn,
                petal_tilt=pf,
                petal_separation=ps,
                openness=(ol_in, ol_out),
            )
            fig = generate_red_rose(params)
        else:
            params = WaterLilyParams(
                num_petals=npetals,
                vertices_per_petal_theta=vpp,
                vertices_per_petal_r=vrpp,
                petal_colors=name_to_lily_colors(name or "Anonymous"),
            )
            fig = generate_water_lily(params)

        buf = io.BytesIO()
        fig.savefig(buf, format="png", dpi=150, bbox_inches="tight", transparent=True)
        # Water lilies float on water — no stem
        if _flower_key == "Water Lily":
            image_bytes = buf.getvalue()
        else:
            image_bytes = compose_with_stem(buf.getvalue())

        # Store in session state so the Garden page can use it
        st.session_state["flower_params"] = params
        st.session_state["flower_b64"] = base64.b64encode(image_bytes).decode()
        st.session_state["flower_name"] = name or "Anonymous"

    col, _ = st.columns([1, 1])
    with col:
        st.pyplot(fig)
        st.download_button("Télécharger PNG" if fr else "Download PNG", image_bytes, "my_flower.png", "image/png")
        if name:
            st.success("Va dans la page Garden pour planter ta fleur !" if fr else "Head to the Garden page to plant your flower!")
        else:
            st.info("Entre ton prénom ci-dessus pour pouvoir la planter dans le jardin." if fr else "Enter your name above to be able to plant it in the garden.")
